spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost/gerenciador_eventos?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
